//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outlands_Adventure_Launcher {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ClientLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientLanguage() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Outlands_Adventure_Launcher.ClientLanguage", typeof(ClientLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        internal static string button_Close_Lowercase {
            get {
                return ResourceManager.GetString("button_Close_Lowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CERRAR.
        /// </summary>
        internal static string button_Close_Uppercase {
            get {
                return ResourceManager.GetString("button_Close_Uppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ENVIAR.
        /// </summary>
        internal static string button_Confirm {
            get {
                return ResourceManager.GetString("button_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprar.
        /// </summary>
        internal static string buy_Button {
            get {
                return ResourceManager.GetString("buy_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juego comprado con éxito.
        /// </summary>
        internal static string buyGameSucess {
            get {
                return ResourceManager.GetString("buyGameSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a €.
        /// </summary>
        internal static string currency {
            get {
                return ResourceManager.GetString("currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saldo Actual.
        /// </summary>
        internal static string currentCurrency {
            get {
                return ResourceManager.GetString("currentCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio del juego.
        /// </summary>
        internal static string currentGamePrice {
            get {
                return ResourceManager.GetString("currentGamePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En cola  --  Prioridad.
        /// </summary>
        internal static string currentPriority {
            get {
                return ResourceManager.GetString("currentPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargas.
        /// </summary>
        internal static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar.
        /// </summary>
        internal static string download_Avaible_Button {
            get {
                return ResourceManager.GetString("download_Avaible_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar descarga.
        /// </summary>
        internal static string download_cancel {
            get {
                return ResourceManager.GetString("download_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En curso.
        /// </summary>
        internal static string download_InProgress {
            get {
                return ResourceManager.GetString("download_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No disponible.
        /// </summary>
        internal static string download_Unavaible_Button {
            get {
                return ResourceManager.GetString("download_Unavaible_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código erroneo.
        /// </summary>
        internal static string eventCode_Error {
            get {
                return ResourceManager.GetString("eventCode_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha producido un error al acceder a la base de datos, compruebe su conexión a internet e intentelo de nuevo más tarde.
        /// </summary>
        internal static string events_Database_ConnectionError {
            get {
                return ResourceManager.GetString("events_Database_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hemos mandado un código de confirmación a tu correo electrónico, dirígete a tu correo e introduce el código para confirmar tu cuenta.
        /// </summary>
        internal static string events_Header_NewAccount {
            get {
                return ResourceManager.GetString("events_Header_NewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si la dirección de correo coincide con alguna dirección de correo de nuestra base de datos te enviaremos un código de confirmación para que reestablezcas tu contraseña.
        /// </summary>
        internal static string events_Header_PasswordLost {
            get {
                return ResourceManager.GetString("events_Header_PasswordLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si la dirección de correo coincide con alguna dirección de correo de nuestra base de datos te mandaremos un recordatorio de tu nombre de usuario.
        /// </summary>
        internal static string events_Header_UsernameLost {
            get {
                return ResourceManager.GetString("events_Header_UsernameLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un problema al enviar el correo, compruebe su conexión a internet e intentelo de nuevo más tarde.
        /// </summary>
        internal static string events_SendEmailError {
            get {
                return ResourceManager.GetString("events_SendEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿SALIR AHORA?.
        /// </summary>
        internal static string exit_Header {
            get {
                return ResourceManager.GetString("exit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres salir o cerrar sesión?.
        /// </summary>
        internal static string exit_Label {
            get {
                return ResourceManager.GetString("exit_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string ExitButton {
            get {
                return ResourceManager.GetString("ExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar biblioteca.
        /// </summary>
        internal static string filterGame {
            get {
                return ResourceManager.GetString("filterGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ERROR AL DESCARGAR.
        /// </summary>
        internal static string game_DownloadError {
            get {
                return ResourceManager.GetString("game_DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargando.
        /// </summary>
        internal static string game_Downloading_LowerCase {
            get {
                return ResourceManager.GetString("game_Downloading_LowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DESCARGANDO.
        /// </summary>
        internal static string game_Downloading_Uppercase {
            get {
                return ResourceManager.GetString("game_Downloading_Uppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DESCARGA COMPLETA.
        /// </summary>
        internal static string game_DownloadSucess {
            get {
                return ResourceManager.GetString("game_DownloadSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSTALANDO.
        /// </summary>
        internal static string game_Install {
            get {
                return ResourceManager.GetString("game_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ERROR AL INSTALAR.
        /// </summary>
        internal static string game_InstallError {
            get {
                return ResourceManager.GetString("game_InstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ESPACIO INSUFICIENTE.
        /// </summary>
        internal static string game_NoSpace {
            get {
                return ResourceManager.GetString("game_NoSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Biblioteca de juegos.
        /// </summary>
        internal static string gameLibrary_Header {
            get {
                return ResourceManager.GetString("gameLibrary_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reparar.
        /// </summary>
        internal static string gameSettingsMenu_Repair {
            get {
                return ResourceManager.GetString("gameSettingsMenu_Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desinstalar.
        /// </summary>
        internal static string gameSettingsMenu_Uninstall {
            get {
                return ResourceManager.GetString("gameSettingsMenu_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string gameSettingsMenu_Update {
            get {
                return ResourceManager.GetString("gameSettingsMenu_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En cola.
        /// </summary>
        internal static string InQueue {
            get {
                return ResourceManager.GetString("InQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iconos grandes.
        /// </summary>
        internal static string largeTiles_Tooltip {
            get {
                return ResourceManager.GetString("largeTiles_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se han encontrado juegos en la librería.
        /// </summary>
        internal static string LibraryEmpty {
            get {
                return ResourceManager.GetString("LibraryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tus credenciales de inicio de sesión no coinciden con ninguna cuenta registrada en nuestro sistema.
        /// </summary>
        internal static string login_Error {
            get {
                return ResourceManager.GetString("login_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicia sesión con tu cuenta de Outlands Adventure.
        /// </summary>
        internal static string login_Header {
            get {
                return ResourceManager.GetString("login_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Problemas al iniciar sesión?.
        /// </summary>
        internal static string login_LoginProblems {
            get {
                return ResourceManager.GetString("login_LoginProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear una cuenta.
        /// </summary>
        internal static string login_Register {
            get {
                return ResourceManager.GetString("login_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantener sesión abierta.
        /// </summary>
        internal static string login_RememberMe {
            get {
                return ResourceManager.GetString("login_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿PROBLEMAS AL INICIAR SESIÓN?.
        /// </summary>
        internal static string loginProblems_Header {
            get {
                return ResourceManager.GetString("loginProblems_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay diversas razones por las que no puedas inicar sesión, prueba las siguientes soluciones.
        /// </summary>
        internal static string loginProblems_Header2 {
            get {
                return ResourceManager.GetString("loginProblems_Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        internal static string loginProblems_Login {
            get {
                return ResourceManager.GetString("loginProblems_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Has olvidado tu contraseña? Puedes solicitar cambiar tu contraseña anterior por otra nueva.
        /// </summary>
        internal static string loginProblems_LostPassword {
            get {
                return ResourceManager.GetString("loginProblems_LostPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Necesitas ayuda para recordar tu nombre de usuario? Puedes solicitar que te mandemos un recordatorio de tu usuario a tu correo electrónico.
        /// </summary>
        internal static string loginProblems_LostUsername {
            get {
                return ResourceManager.GetString("loginProblems_LostUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Contraseña olvidada?.
        /// </summary>
        internal static string loginProblems_PasswordHeader {
            get {
                return ResourceManager.GetString("loginProblems_PasswordHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Nombre de usuario olvidado?.
        /// </summary>
        internal static string loginProblems_UsernameHeader {
            get {
                return ResourceManager.GetString("loginProblems_UsernameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        internal static string LogoutButton {
            get {
                return ResourceManager.GetString("LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iconos medianos.
        /// </summary>
        internal static string mediumTiles_Tooltip {
            get {
                return ResourceManager.GetString("mediumTiles_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe tu nueva contraseña.
        /// </summary>
        internal static string newPasswordEvent_Header {
            get {
                return ResourceManager.GetString("newPasswordEvent_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NUEVA CONTRASEÑA.
        /// </summary>
        internal static string newPasswordEvent_Password {
            get {
                return ResourceManager.GetString("newPasswordEvent_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña cambiada con éxito.
        /// </summary>
        internal static string newPasswordSucessful {
            get {
                return ResourceManager.GetString("newPasswordSucessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay juegos descargandose.
        /// </summary>
        internal static string NoCurrentDownloading {
            get {
                return ResourceManager.GetString("NoCurrentDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay juegos en la cola de descargas.
        /// </summary>
        internal static string NoDownloadQueue {
            get {
                return ResourceManager.GetString("NoDownloadQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a descargas.
        /// </summary>
        internal static string Open_DownloadsInformation {
            get {
                return ResourceManager.GetString("Open_DownloadsInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mediana.
        /// </summary>
        internal static string passwordStrenght_Medium {
            get {
                return ResourceManager.GetString("passwordStrenght_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fuerte.
        /// </summary>
        internal static string passwordStrenght_Strong {
            get {
                return ResourceManager.GetString("passwordStrenght_Strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Muy fuerte.
        /// </summary>
        internal static string passwordStrenght_VeryStrong {
            get {
                return ResourceManager.GetString("passwordStrenght_VeryStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Muy débil.
        /// </summary>
        internal static string passwordStrenght_VeryWeak {
            get {
                return ResourceManager.GetString("passwordStrenght_VeryWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Débil.
        /// </summary>
        internal static string passwordStrenght_Weak {
            get {
                return ResourceManager.GetString("passwordStrenght_Weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar.
        /// </summary>
        internal static string play_Button {
            get {
                return ResourceManager.GetString("play_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disminuir prioridad de la descarga.
        /// </summary>
        internal static string priorityDown {
            get {
                return ResourceManager.GetString("priorityDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aumentar prioridad de la descarga.
        /// </summary>
        internal static string priorityUp {
            get {
                return ResourceManager.GetString("priorityUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aleatorio.
        /// </summary>
        internal static string randomDefaultScreen {
            get {
                return ResourceManager.GetString("randomDefaultScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crea tu cuenta de Outlands Adventure.
        /// </summary>
        internal static string register_Header {
            get {
                return ResourceManager.GetString("register_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Ya tienes una cuenta? Inicia sesión.
        /// </summary>
        internal static string register_Login {
            get {
                return ResourceManager.GetString("register_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Te has registrado exitosamente.
        /// </summary>
        internal static string registerSucessful {
            get {
                return ResourceManager.GetString("registerSucessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminación de la cuenta del cliente de Outlands Adventure*Su código de confimación es.
        /// </summary>
        internal static string sendEmail_DeleteAccount {
            get {
                return ResourceManager.GetString("sendEmail_DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reestablecimiento de la contraseña del cliente de Outlands Adventure*Su código de confimación es.
        /// </summary>
        internal static string sendEmail_LostPassword {
            get {
                return ResourceManager.GetString("sendEmail_LostPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recordatorio del nombre de usuario del cliente de Outlands Adventure*Su nombre de usuario es.
        /// </summary>
        internal static string sendEmail_LostUsername {
            get {
                return ResourceManager.GetString("sendEmail_LostUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creación de una nueva cuenta del cliente de Outlands Adventure*Su código de confimación es.
        /// </summary>
        internal static string sendEmail_NewAccount {
            get {
                return ResourceManager.GetString("sendEmail_NewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Biblioteca de juegos*Tienda*Aleatorio.
        /// </summary>
        internal static string settings_DefaultScreen {
            get {
                return ResourceManager.GetString("settings_DefaultScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pantalla de inicio.
        /// </summary>
        internal static string settings_DefaultScreenHeader {
            get {
                return ResourceManager.GetString("settings_DefaultScreenHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar cuenta.
        /// </summary>
        internal static string settings_DeleteAccount {
            get {
                return ResourceManager.GetString("settings_DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AJUSTES.
        /// </summary>
        internal static string settings_Header {
            get {
                return ResourceManager.GetString("settings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma del cliente.
        /// </summary>
        internal static string settings_LanguageHeader {
            get {
                return ResourceManager.GetString("settings_LanguageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ESPAÑOL - ESPAÑA (es-ES)*INGLÉS - ESTADOS UNIDOS (en-US)*INGLÉS - REINO UNIDO (en-GB)*FRANCÉS (fr)*ALEMÁN (de)*RUSO (ru)*JAPONÉS (ja)*NORUEGO (no).
        /// </summary>
        internal static string settings_Languages {
            get {
                return ResourceManager.GetString("settings_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iconos pequeños.
        /// </summary>
        internal static string smallTiles_Tooltip {
            get {
                return ResourceManager.GetString("smallTiles_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tienda.
        /// </summary>
        internal static string store_Header {
            get {
                return ResourceManager.GetString("store_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se han encontrado juegos nuevos.
        /// </summary>
        internal static string StoreEmpty {
            get {
                return ResourceManager.GetString("StoreEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REPITE LA CONTRASEÑA.
        /// </summary>
        internal static string textbox_ConfirmPassword {
            get {
                return ResourceManager.GetString("textbox_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DIRECCIÓN DE CORREO.
        /// </summary>
        internal static string textbox_Email {
            get {
                return ResourceManager.GetString("textbox_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONTRASEÑA.
        /// </summary>
        internal static string textbox_Password {
            get {
                return ResourceManager.GetString("textbox_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOMBRE DE USUARIO.
        /// </summary>
        internal static string textbox_Username {
            get {
                return ResourceManager.GetString("textbox_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección de correo ya registrada.
        /// </summary>
        internal static string textboxError_EmailRegistered {
            get {
                return ResourceManager.GetString("textboxError_EmailRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe contener cuatro letras como mínimo.
        /// </summary>
        internal static string textboxError_LessFourLetters {
            get {
                return ResourceManager.GetString("textboxError_LessFourLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden.
        /// </summary>
        internal static string textboxError_PasswordNotMatch {
            get {
                return ResourceManager.GetString("textboxError_PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario ya registrado.
        /// </summary>
        internal static string textboxError_UsernameRegistered {
            get {
                return ResourceManager.GetString("textboxError_UsernameRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce una dirección de correo válida.
        /// </summary>
        internal static string textboxError_WrongEmail {
            get {
                return ResourceManager.GetString("textboxError_WrongEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desinstalado.
        /// </summary>
        internal static string Uninstalled_Game {
            get {
                return ResourceManager.GetString("Uninstalled_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desinstalando.
        /// </summary>
        internal static string Uninstalling_Game {
            get {
                return ResourceManager.GetString("Uninstalling_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        internal static string userInfoMenu_logout {
            get {
                return ResourceManager.GetString("userInfoMenu_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ajustes de la aplicación.
        /// </summary>
        internal static string userInfoMenu_Settings {
            get {
                return ResourceManager.GetString("userInfoMenu_Settings", resourceCulture);
            }
        }
    }
}
